config/routes.rb
Rails.application.routes.draw do
  resources :stresses
  resources :moods
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/stresses_controller.rb
class StressesController < ApplicationController
  before_action :set_stress, only: [:show, :edit, :update, :destroy]

  # GET /stresses
  # GET /stresses.json
  def index
    @stresses = Stress.all
  end

  # GET /stresses/1
  # GET /stresses/1.json
  def show
  end

  # GET /stresses/new
  def new
    @stress = Stress.new
  end

  # GET /stresses/1/edit
  def edit
  end

  # POST /stresses
  # POST /stresses.json
  def create
    @stress = Stress.new(stress_params)

    respond_to do |format|
      if @stress.save
        format.html { redirect_to @stress, notice: 'Stress was successfully created.' }
        format.json { render :show, status: :created, location: @stress }
      else
        format.html { render :new }
        format.json { render json: @stress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stresses/1
  # PATCH/PUT /stresses/1.json
  def update
    respond_to do |format|
      if @stress.update(stress_params)
        format.html { redirect_to @stress, notice: 'Stress was successfully updated.' }
        format.json { render :show, status: :ok, location: @stress }
      else
        format.html { render :edit }
        format.json { render json: @stress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stresses/1
  # DELETE /stresses/1.json
  def destroy
    @stress.destroy
    respond_to do |format|
      format.html { redirect_to stresses_url, notice: 'Stress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stress
      @stress = Stress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stress_params
      params.require(:stress).permit(:user_id, :date, :stress)
    end
end

app/helpers/stresses_helper.rb
module StressesHelper
end

app/views/stresses/_form.html.erb
<%= form_with(model: stress, local: true) do |form| %>
  <% if stress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stress.errors.count, "error") %> prohibited this stress from being saved:</h2>

      <ul>
        <% stress.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :stress %>
    <%= form.number_field :stress %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stresses/edit.html.erb
<h1>Editing Stress</h1>

<%= render 'form', stress: @stress %>

<%= link_to 'Show', @stress %> |
<%= link_to 'Back', stresses_path %>

app/views/stresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stresses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Stress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stresses.each do |stress| %>
      <tr>
        <td><%= stress.user_id %></td>
        <td><%= stress.date %></td>
        <td><%= stress.stress %></td>
        <td><%= link_to 'Show', stress %></td>
        <td><%= link_to 'Edit', edit_stress_path(stress) %></td>
        <td><%= link_to 'Destroy', stress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stress', new_stress_path %>

app/views/stresses/new.html.erb
<h1>New Stress</h1>

<%= render 'form', stress: @stress %>

<%= link_to 'Back', stresses_path %>

app/views/stresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @stress.user_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @stress.date %>
</p>

<p>
  <strong>Stress:</strong>
  <%= @stress.stress %>
</p>

<%= link_to 'Edit', edit_stress_path(@stress) %> |
<%= link_to 'Back', stresses_path %>