config/routes.rb
Rails.application.routes.draw do
  resources :stresses
  resources :moods
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mood.rb
class Mood < ApplicationRecord
  belongs_to :user

  def self.import_file
    return Rails.root.join('spec','fixtures','dataset','moods.csv') if Rails.env == 'test'
    Rails.root.join('app','dataset','moods.csv')
  end

  def self.import_from_csv
    table = CSV.parse(File.read(Mood.import_file), headers: true)
    table.by_row.each do |row|
      Mood.create(user_id: row["userid"], date: row["date"], mood: row["mood"], description: row["description"])
    end
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mood_params
      params.require(:mood).permit(:user_id, :date, :mood, :description)
    end
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/moods/_form.html.erb
<%= form_with(model: mood, local: true) do |form| %>
  <% if mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
        <% mood.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :mood %>
    <%= form.number_field :mood %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Show', @mood %> |
<%= link_to 'Back', moods_path %>

app/views/moods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moods</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Date</th>
      <th>Mood</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moods.each do |mood| %>
      <tr>
        <td><%= mood.user_id %></td>
        <td><%= mood.date %></td>
        <td><%= mood.mood %></td>
        <td><%= mood.description %></td>
        <td><%= link_to 'Show', mood %></td>
        <td><%= link_to 'Edit', edit_mood_path(mood) %></td>
        <td><%= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mood', new_mood_path %>

app/views/moods/new.html.erb
<h1>New Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Back', moods_path %>

app/views/moods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @mood.user_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @mood.date %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @mood.mood %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mood.description %>
</p>

<%= link_to 'Edit', edit_mood_path(@mood) %> |
<%= link_to 'Back', moods_path %>